{{- if .Values.fabric.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cybrik-platform.fullname" . }}-fabric
  labels:
    {{- include "cybrik-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: fabric
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.fabric.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "cybrik-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: fabric
{{- end }}
